### ISSUE TITLE
四个图标的正常摆放,相同间隔问题,以及图片的padding问题

### ISSUE THREAD

**Issue by wagnlinzh** [FED-Div/task3#1]
log: 大致完成了结构部署,我觉得这一个任务最主要的是学习float的用法

里面有两个地方我的做法不太好,求讨论
- 关于第三栏4 个logo的摆放,我用到了css3的属性,我觉得应该有可以不用css3 的办法
- 关于图片的border我用到了margin,但任务要求是用padding,

在使用padding的时候会出现如下图的情况

![task3](https://cloud.githubusercontent.com/assets/3985726/13898166/e3c9b398-ee03-11e5-9c34-48feafa5c00b.png)

**Comment by izayl** [comment]
试试box-sizing: border-box

**Comment by wagnlinzh** [comment]
恩恩,这个属性是可以的,

我还搜到一篇博客http://sunyuhui.com/box-sizing/

## 

但是这么做又有另外一个问题, 就是四个图片中第一张图片最上位置的 间距和第四张图片最下位置的间距分别是20,但是其他图片之间的间距是40.

还是如图
![2](https://cloud.githubusercontent.com/assets/3985726/13898597/2ffac97a-ee11-11e5-8687-77b1766414e9.png)

**Comment by izayl** [comment]
可以在容器里加padding

**Comment by wagnlinzh** [comment]
还有一种方法,就是将img设置为display:block,这样margin值就不会相加了,代码如下:

``` css
.right_col img{
    display: block;
    width: 80px;
    height: 80px;
    margin:20px;
    border:1px solid #999;
}
```
